# this file is only used for GitHub
# it is not related to your Kafka Streams learning

language: scala
jdk: openjdk8
scala:
  - 2.12.8

script:
# test the java components
- cd kafka-streams-java && mvn clean verify
# test the scala components
- cd ../kafka-streams-scala && sbt clean test

